AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sporticulture-SS-Automation

  Sample SAM Template for Sporticulture-SS-Automation

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 480 # 8 minutes in seconds
    MemorySize: 128

    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources:
  SPFailedOrdersDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SPFailedOrdersDLQ.fifo  # Updated to FIFO
      FifoQueue: true  

  SporticultureOrderQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SporticultureOrderQueue.fifo  # Updated to FIFO
      FifoQueue: true 
      VisibilityTimeout: 480
      RedrivePolicy:
        maxReceiveCount: 3
        deadLetterTargetArn: !GetAtt SPFailedOrdersDLQ.Arn

  SporticultureOrderQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref SporticultureOrderQueue  # Corrected reference
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: sqs:SendMessage
            Resource: !GetAtt SporticultureOrderQueue.Arn  # Corrected resource
            Principal: "*"

  SPBatchLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sp_batch_lambda/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Timeout: 480
      # Removed Role property

  SporticultureMainLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: main_lambda/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Events:
        SporticultureOrderQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SporticultureOrderQueue.Arn
      # Removed Role property

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
